### ISSUE TITLE
some bugs

### ISSUE THREAD

**Issue by quantumbagel** [USSyorktown10/STF-Captains-Chair#1]
### README Typos
`Avalible Features: Approx. 5/11`
` (Game currcency) yet.`
there are some other questionable wordings, but that's all you need to change

### Code
- add `requirements.txt` (see here https://www.freecodecamp.org/news/python-requirementstxt-explained/)
- Rename "STF Main" to "stf_main.py" so there is syntax highlighting
- Consistent naming: write variables like `some_variable` instead of `someVariable`, `SomeVariable`, `Some_Variable`, or `somevariable`
- Unused library "keyboard" - this isn't a default library, and importing is not needed
- what in the heck is the "Yes" variable, you can just do `while True:` or even `while 1:`
- I had a crash when attacking a Klingon ship in the Delta Sector:
`Traceback (most recent call last):
  File "/home/jjreder/stf.py", line 570, in <module>
    print(f'{Fore.BLUE}Vulcan Health:{Fore.WHITE}', KlingHealth)
                                                    ^^^^^^^^^^^
NameError: name 'KlingHealth' is not defined
jjreder@penguin:~$ `
you need to sanitize inputs (typing non-ints or ints too big or small causes crashes

Fix this stuff, and I will help with optimization. 
I would love a way to 
- have some progression sense
- see coins at each screen
- saving between runs
other than that, really cool!

**Comment by quantumbagel** [comment]
Progress on this issue:

## completed
- requirements.txt added
- renamed file
- keyboard removed
- Yes variable removed
- klingon crash fixed

## not fixed
- sanitization of inputs
- consistent naming

piece of advice - you can reference an issue in your commits by typing #1 (this issue) or #2 (haha have more bugs)

**Comment by USSyorktown10** [comment]
Just curious - what do you mean by sanatization of inputs?

**Comment by quantumbagel** [comment]
Sanitization means only allowing valid inputs without crashing. (like only integers between 1 and 10 for the battle system)

**Comment by USSyorktown10** [comment]
I do have valid then, because it can handle any number, it will just miss if its too big.

**Comment by USSyorktown10** [comment]
so yeah, i am still very confused on what you mean by this. do you have any specific examples?

**Comment by quantumbagel** [comment]
https://www.reddit.com/r/learnpython/comments/utlqum/please_advise_how_to_sanitize_input_for_int_other/

**Comment by USSyorktown10** [comment]
can you just type out the important stuff? its blocked for me.

**Comment by quantumbagel** [comment]
<img width="944" alt="Screenshot 2024-08-30 at 3 51 16 PM" src="https://github.com/user-attachments/assets/92c1dc20-9140-410a-8ec0-bb1c659da957">

**Comment by quantumbagel** [comment]
<img width="778" alt="Screenshot 2024-08-30 at 3 52 46 PM" src="https://github.com/user-attachments/assets/b9d61df5-4a64-48bb-8614-1cc0072d7305">

**Comment by quantumbagel** [comment]
I would functionize this tho
