### ISSUE TITLE
Making a Release (quantum bagel)

### ISSUE THREAD

**Issue by USSyorktown10** [USSyorktown10/STF-Captains-Chair#3]
How do I make a release that will run the game for you in this? This is probably the shortest issue ever written, but I need help.

`- USSyorktown10`

**Comment by quantumbagel** [comment]
I don't know what "run the game for you in this" means lol

Do you mean packaging it as EXE?

**Comment by USSyorktown10** [comment]
I guess, but I was thinking somehteing where you open the release and it runs the game, so like an HTML with a python interpreter but it shows only the terminal

**Comment by quantumbagel** [comment]
still confused lol
Try to find something else doing the thing you want it to

**Comment by USSyorktown10** [comment]
Maybe like releasing a package or something
Basically something where you don't have to copy and paste all the code into a python interpreter and terminal, I was wanting something where you just open the link/app, and it runs the test immediately
