### ISSUE TITLE
Battle system outline

### ISSUE THREAD

**Issue by quantumbagel** [USSyorktown10/STF-Captains-Chair#4]
You need a better battling system.

Here's an outline of what you need in a function for battling (pseudocode)

- def battle(opponent_health, opponent_name, opponent_strength, riches)
- print "You are battling {opponent_name} now. they have {opponent_health} and have {riches} riches"
- while nobody ded
- calculate damage (don't take input)
- calculate opponent dodge
- update
- print("you did damage or you missed I'm lazy")
- repeat with opponent
- continue until ded
- print('you lost or you didn't)
-  print( maybe you gained money / resources)
- add money to bank account
- return whether you won

Try to write code for a function based on this.

**Comment by USSyorktown10** [comment]
I am confused on what you mean my calculate damage and calculate opponent dodge. I think that the current battle system is fine, but are you asking me to make a battle simulator that will run the entire thing for you? Also, this is the code i have added so far:
`def battle(opponent_health, opponent_name, oppenent_damage, income):
    
print('You are attacking the ', opponent_name, ' ! This ship has ', opponent_health, ' health, and if you win, you get ', income, '.')
    
while Health > 0:`

**Comment by quantumbagel** [comment]
for MarkDown, you need three backticks for multiline code

like this

```
hi

yo
```

I'm asking you to make a function that handles the battle (which you are doing). I'm just saying that I don't personally like the attack system (what about items you can buy like a missile launch or something different?). You could also make it so it has different opponent strengths - and there doesn't seem to be a tangible reward from actually killing these people.

calculate damage means 

- take input from player
- get the dodge number from the bot
- determine if there's a hit
- do damage

You already have this in your code.

let me know if you got any questions

**Comment by USSyorktown10** [comment]
Ah, I see what you mean now. I just reuse the code, but instead of the variables being case specific to the ship, they are the `opponent_health` variable. Makes sense now.
Also, I did have different strengths, but yes, there is no reward for winning. (currently)

**Comment by USSyorktown10** [comment]
Alright, I finished the battle function and have committed. Next, I need to integrate it. You look over it and tell me how its looking, give me some suggestions, then once thats fixed, you can show me how to integrate it with the actual battles.
(I can already see how this is gonna make things so much easier. If I want to make the game more playable, its much easier to find the code and easier to fix then the current system.)

**Comment by USSyorktown10** [comment]
Finished the battle function, all of it is functional. If there is anything else you want added to it, just tell me, or I can close the issue if its finnaly done.
