### ISSUE TITLE
Progression

### ISSUE THREAD

**Issue by quantumbagel** [USSyorktown10/STF-Captains-Chair#8]
This game needs progression to feel fun. 

Ways you could add this:

- leaderboard/multiplayer (no chance probably)
- Ability to unlock new sectors with better rewards
- Lore
- Quests
- Microtransactions (lol jk)
- a more rewarding upgrade system

Right now, the game is only engaging for about five minutes, and the entirely RNG based battle system means there is literally no skill involved. I would love there to be some greater sense of strategy in this game. I'm hoping this thread can be used more as a discussion of ideas than direct implementation - what you have works, just not effectively.

**Comment by USSyorktown10** [comment]
I do like the new sectors, the lore might be hard to make, but ill try to figure it out, quests are coming soon and i was planning on making them in the first place, and the upgrading system will be better. I will add all of this to my apple note thing that you are added to, and I will DEFENITLY try to add microtransactions

**Comment by USSyorktown10** [comment]
New sectors and better rewards being added with warp range
Gonna think up Lore, still working on it
Missions are underway, trying to make them too,
ships are being added for better play.
